---
- name: install Jenkins & Java on Machine 1
  become: true
  hosts: localhost
  tasks:
  - name: running jenkins_install
    script: jenkins_java_install.sh

- name: install Java, Docker & Kubernetes on Machine-2
  become: true
  hosts: master
  tasks:
  - name: running install_java_docker_k8
    script: install_java_docker_k8.sh

- name: install Docker & Kubernetes on Machine-3&4
  become: true
  hosts: slaves
  tasks:
  - name: running docker_k8_install
    script: docker_k8_install.sh
